### ISSUE TITLE
Configure Prometheus parameters are not correct

### ISSUE THREAD

**Issue by ltouro** [weaveworks/cortex#473]
Using the proposed config for Prometheus does not work in latest Prometheus. Their config API is changing, I think.

```
remote_write:
  url: https://cloud.weave.works/api/prom/push
  basic_auth:
    password: somekey
```
Results in this error:

```
time="2017-07-01T12:26:20Z" level=error msg="Error loading config: couldn't load configuration (-config.file=/etc/prometheus/prometheus.yml): yaml: unmarshal errors:
  line 2: cannot unmarshal !!map into []*config.RemoteWriteConfig" source="main.go:160"
```
Using this version works:

```
remote_write:
  - url: https://cloud.weave.works/api/prom/push
    basic_auth:
      password: somekey
```
